name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Install dependencies
      run: npm i
    - name: Run lint
      run: npm run lint
    - name: Run test
      run: npm test
    - name: Test build
      run: npm run build