name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run test
      run: npm run test