name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run test
      run: npm run test