name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: "12.x"
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != true
      run: npm i
    - name: Run lint
      run: npm run lint
    - name: Run test
      run: npm test
    - name: Test build
      run: npm run build